export const INIT_APP = 'INIT_APP';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const VOTE_ITEM = 'VOTE_ITEM';
export const UPDATE_NEW_ITEM = 'UPDATE_NEW_ITEM';
export const CLEAR_NEW_ITEM = 'CLEAR_NEW_ITEM';

export const CALL_API = 'CALL_API';

export const FETCH_SWOTS = 'FETCH_SWOTS';
export const FETCH_SWOTS_SUCCESS = 'FETCH_SWOTS_SUCCESS';
export const FETCH_SWOTS_ERROR = 'FETCH_SWOTS_ERROR';

export const CREATE_SWOT = 'CREATE_SWOT';
export const CREATE_SWOT_SUCCESS = 'CREATE_SWOT_SUCCESS';
export const CREATE_SWOT_ERROR = 'CREATE_SWOT_ERROR';

export const UPDATE_SWOT = 'UPDATE_SWOT';
export const UPDATE_SWOT_SUCCESS = 'UPDATE_SWOT_SUCCESS';
export const UPDATE_SWOT_ERROR = 'UPDATE_SWOT_ERROR';

export const DELETE_SWOT = 'DELETE_SWOT';
export const DELETE_SWOT_SUCCESS = 'DELETE_SWOT_SUCCESS';
export const DELETE_SWOT_ERROR = 'DELETE_SWOT_ERROR';

export const FETCH_SWOT_ITEMS = 'FETCH_SWOT_ITEMS';
export const FETCH_SWOT_ITEMS_SUCCESS = 'FETCH_SWOT_ITEMS_SUCCESS';
export const FETCH_SWOT_ITEMS_ERROR = 'FETCH_SWOT_ITEMS_ERROR';

export const CREATE_SWOT_ITEM = 'CREATE_SWOT_ITEM';
export const CREATE_SWOT_ITEM_SUCCESS = 'CREATE_SWOT_ITEM_SUCCESS';
export const CREATE_SWOT_ITEM_ERROR = 'CREATE_SWOT_ITEM_ERROR';

export const UPDATE_SWOT_ITEM = 'UPDATE_SWOT_ITEM';
export const UPDATE_SWOT_ITEM_SUCCESS = 'UPDATE_SWOT_ITEM_SUCCESS';
export const UPDATE_SWOT_ITEM_ERROR = 'UPDATE_SWOT_ITEM_ERROR';

export const DELETE_SWOT_ITEM = 'DELETE_SWOT_ITEM';
export const DELETE_SWOT_ITEM_SUCCESS = 'DELETE_SWOT_ITEM_SUCCESS';
export const DELETE_SWOT_ITEM_ERROR = 'DELETE_SWOT_ITEM_ERROR';

export const FETCH_VOTES = 'FETCH_VOTES';
export const FETCH_VOTES_SUCCESS = 'FETCH_VOTES_SUCCESS';
export const FETCH_VOTES_ERROR = 'FETCH_VOTES_ERROR';

export const VOTE = 'VOTE';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_ERROR = 'VOTE_ERROR';

export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_ERROR = 'FETCH_MEMBERS_ERROR';

export const LOAD_TOKEN = 'LOAD_TOKEN';