# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('swot', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='swotitem',
      name='vote',
      field=models.PositiveIntegerField(default=0),
      preserve_default=False,
    ),
    migrations.AddField(
      model_name='swotitem',
      name='voted',
      field=models.BooleanField(default=False),
    ),
  ]
