# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('swot', '0002_auto_20170821_2153'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='swotitem',
      name='vote',
    ),
    migrations.RemoveField(
      model_name='swotitem',
      name='voted',
    ),
  ]
