# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ('swot', '0003_auto_20170912_0321'),
  ]

  operations = [
    migrations.CreateModel(
      name='UpVote',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created', models.DateTimeField(auto_now_add=True)),
      ],
    ),
    migrations.RenameModel(
      old_name='SwotItem',
      new_name='Item',
    ),
    migrations.AddField(
      model_name='upvote',
      name='item',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swot.Item'),
    ),
  ]
