# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('swot', '0005_auto_20180226_0255'),
  ]

  operations = [
    migrations.RenameModel(
      old_name='Item',
      new_name='SwotItem',
    ),
  ]
